# Generated by Django 4.2.17 on 2025-01-01 23:42

from django.db import migrations, models
import django.db.models.deletion
import ftp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=ftp.models.generate_room_code, max_length=8, unique=True)),
                ('host', models.CharField(default='', max_length=50, unique=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.CharField(default='', max_length=50, unique=True)),
                ('name', models.CharField(default='', max_length=20)),
                ('is_host', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftp.room')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomFile', models.FileField(upload_to=ftp.models.get_file_path)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftp.room')),
            ],
        ),
    ]
