# Generated by Django 3.2.6 on 2021-08-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0002_guests_guest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='host',
            new_name='guest',
        ),
        migrations.AddField(
            model_name='room',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Guests',
        ),
    ]
