# Generated by Django 3.2.6 on 2021-08-21 09:46

from django.db import migrations, models
import ftp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0003_auto_20210821_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=ftp.models.generate_room_code, max_length=8),
        ),
    ]
