# Generated by Django 3.2.6 on 2021-08-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0004_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
