# Generated by Django 3.2.6 on 2021-08-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0008_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
