# Generated by Django 3.2.6 on 2021-08-21 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0009_alter_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest',
            new_name='host',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_host',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.CharField(default='', max_length=50, unique=True)),
                ('name', models.CharField(default='', max_length=20)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftp.room')),
            ],
        ),
    ]
