# Generated by Django 3.2.6 on 2021-08-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0010_auto_20210822_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
