# Generated by Django 3.2.6 on 2021-08-21 21:47

from django.db import migrations, models
import ftp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0011_guest_is_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='code',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=ftp.models.generate_room_code, max_length=8, unique=True),
        ),
    ]
