# Generated by Django 3.2.6 on 2021-09-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0019_auto_20210830_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='downloadURL',
            field=models.CharField(default='', max_length=100),
        ),
    ]
