# Generated by Django 3.2.6 on 2021-09-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0020_file_downloadurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='downloadURL',
            field=models.TextField(default=''),
        ),
    ]
